# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
- docker build -t udagram-api-frontend ./udagram-api-frontend

# Tagging
- docker tag udagram-api-feed amaruescalante/udagram-api-feed:v1
- docker tag udagram-api-user amaruescalante/udagram-api-user:v1
- docker tag udagram-api-reverseproxy amaruescalante/udagram-api-reverseproxy:v1
- docker tag udagram-api-frontend amaruescalante/udagram-api-frontend:v1

# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push amaruescalante/udagram-api-feed:v1
- docker push amaruescalante/udagram-api-user:v1
- docker push amaruescalante/udagram-api-reverseproxy:v1
- docker push amaruescalante/udagram-api-frontend:v1
