apiVersion: v1
kind: Service
metadata:
  name: backend-reverseproxy-svc
spec:
  selector:
    app: backend-reverseproxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30000
